services:
  backend:
    image: ghcr.io/annuppoudel505-cmyk/backend_repo:latest
    container_name: backend 
    restart: always 
    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - "80:8080"