##build stage 
FROM maven:3.9.16-eclipse-temurin-25 AS build
WORKDIR /app

##copy only the necessary files for building the application
COPY pom.xml .
COPY src ./src

#build jar file 
RUN mvn clean package -DskipTests

#####runtime stage###

FROM eclipse-temurin:25-jre-alpine
WORKDIR /app
#copy the jar file from the build stage
COPY --from=build /app/target/*.jar app.jar

ENV SPRING_PROFILES_ACTIVE=prod

EXPOSE 8080

#healthcheck 
HEALTHCHECK --interval=30s --timeout=3s CMD curl -f http://localhost:8080/ || exit 1

#run the application
ENTRYPOINT ["java", "-jar", "app.jar"]